# Generated by Django 2.2.4 on 2019-08-04 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_auto_20190803_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bought',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bought_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='cart',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
