# Generated by Django 2.2.4 on 2019-08-03 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='score',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
    ]
