# Generated by Django 2.2.4 on 2019-08-03 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
        ('logger', '0002_customuser_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bought',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bought', to='landing.Product'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cart',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cart', to='landing.Product'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='num_added',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='num_bought',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='num_discarded',
            field=models.IntegerField(default=0),
        ),
    ]
