# Generated by Django 2.2.4 on 2019-08-03 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0004_auto_20190803_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bought',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bought', to='landing.Product'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cart',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='landing.Product'),
        ),
    ]
