# Generated by Django 2.2.4 on 2019-08-03 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0006_auto_20190803_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='bought',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='cart',
        ),
    ]
