# Generated by Django 2.2.4 on 2019-08-04 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0007_auto_20190803_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='score',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=10),
        ),
    ]
